export default{
    icHome: require('../../assets/logoimg.png'),
    icCategories: require('../../assets/category.png'),
    icStudio: require('../../assets/live.png'),
    icBrands: require('../../assets/live.png'),
    icProfileshow: require('../../assets/person.png'),
    icAddperson: require('../../assets/person_add.png'),
    icAdd: require('../../assets/user.png'),
    icmen:require('../../assets/young-man.png'),
    ickids:require('../../assets/rock-and-roll.png'),
    icfriend:require('../../assets/friend.png'), 
    icshop:require('../../assets/brand-image.png'),   
    icsale:require('../../assets/shop.jpeg'),  
    icsetting:require('../../assets/settings.png'),                                       
    icearrings:require('../../assets/earrings.png'),                                                                             
}